### ISSUE TITLE
Make breadcrumbs for topic pages

### ISSUE THREAD

**Issue by kmelve** [netliferesearch/u4-no#3]

**Comment by kmelve** [comment]
Send refering page to breadcrumb on longform

**Comment by kmelve** [comment]
Idea: Show related topics if navigating directly to publication?

**Comment by nilsnh** [comment]
See usage example here https://www.geodata.no/produkter-og-tjenester/gis-drift?originId=430

**Comment by nilsnh** [comment]
Housekeeping. Closing as stale issue.
